# Generated by Django 5.2 on 2025-04-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الشركة المنفذة'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرحلة'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='recipient',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المستلم'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='supervisor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المشرف'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المهمة'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.stage'),
        ),
    ]
